### ISSUE TITLE
python3.8 compatibility issue: TypeError: Missing required parameter 'digestmod'.

### ISSUE THREAD

**Issue by CaledoniaProject** [dirkjanm/krbrelayx#13]
dnstool no longer runs with python 3.8

```
[-] Connecting to host...
[-] Binding to host
Traceback (most recent call last):
  File "./dnstool.py", line 536, in <module>
    main()
  File "./dnstool.py", line 364, in main
    if not c.bind():
  File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 563, in bind
    response = self.do_ntlm_bind(controls)
  File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 1302, in do_ntlm_bind
    request = bind_operation(self.version, 'SICILY_RESPONSE_NTLM', ntlm_client, result['server_creds'])
  File "/usr/local/lib/python3.8/dist-packages/ldap3/operation/bind.py", line 81, in bind_operation
    server_creds = name.create_authenticate_message()
  File "/usr/local/lib/python3.8/dist-packages/ldap3/utils/ntlm.py", line 379, in create_authenticate_message
    nt_challenge_response = self.compute_nt_response()
  File "/usr/local/lib/python3.8/dist-packages/ldap3/utils/ntlm.py", line 485, in compute_nt_response
    response_key_nt = self.ntowf_v2()
  File "/usr/local/lib/python3.8/dist-packages/ldap3/utils/ntlm.py", line 497, in ntowf_v2
    return hmac.new(password_digest, (self.user_name.upper() + self.user_domain).encode('utf-16-le')).digest()
  File "/usr/lib/python3.8/hmac.py", line 153, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.8/hmac.py", line 51, in __init__
    raise TypeError("Missing required parameter 'digestmod'.")
TypeError: Missing required parameter 'digestmod'.
```

**Comment by CaledoniaProject** [comment]
https://github.com/SecureAuthCorp/impacket/issues/702

**Comment by dirkjanm** [comment]
This is an issue in the ldap3 library, removing any previous versions and installing the latest should fix it.

**Comment by CaledoniaProject** [comment]
Doesn't look like that way:
https://github.com/slasyz/impacket/commit/8f5ae81532ecc4ed49527a1ecb750d65e4628b10

**Comment by Bobby-Wan** [comment]
Upgraded impacket, removed old ldap3 version, reinstalled, nothing fixes the issue in the hmac.py file. Anything new on the topic ?

**Comment by Moonpiiie** [comment]
> This is an issue in the ldap3 library, removing any previous versions and installing the latest should fix it.

Could you please tell me how to remove the previous ldap3?

**Comment by samuelfaindani** [comment]
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "D:\apps\med-app\models\user.py", line 56, in verify_password
    return check_password_hash(self.password, pwd)
  File "D:\apps\med-app\venv-med\lib\site-packages\werkzeug\security.py", line 219, in check_password_hash
    return hmac.compare_digest(_hash_internal(method, salt, password)[0], hashval)
  File "D:\apps\med-app\venv-med\lib\site-packages\werkzeug\security.py", line 167, in _hash_internal
    return hmac.new(salt, password, method).hexdigest(), method
  File "C:\Users\samue\AppData\Local\Programs\Python\Python39\lib\hmac.py", line 170, in new
    return HMAC(key, msg, digestmod)
  File "C:\Users\samue\AppData\Local\Programs\Python\Python39\lib\hmac.py", line 56, in __init__
    raise TypeError("Missing required parameter 'digestmod'.")
TypeError: Missing required parameter 'digestmod'.

HOW TO FIX THIS IN FLASK APPLICATION,  PLEASE HELP
