### ISSUE TITLE
why is that

### ISSUE THREAD

**Issue by gwqreqherytr** [dirkjanm/krbrelayx#26]
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client HTTP loaded..
[*] Running in attack mode to single host
[*] Running in kerberos relay mode because no credentials were specified.
Traceback (most recent call last):
  File "/root/桌面/krbrelayx-master/krbrelayx.py", line 261, in <module>
    main()
  File "/root/桌面/krbrelayx-master/krbrelayx.py", line 241, in main
    c = start_servers(options, threads)
  File "/root/桌面/krbrelayx-master/krbrelayx.py", line 97, in start_servers
    s = server(c)
  File "/root/桌面/krbrelayx-master/lib/servers/smbrelayserver.py", line 89, in __init__
    self.server = SMBSERVER((config.interfaceIp,445), config_parser = smbConfig)
  File "/usr/lib/python3/dist-packages/impacket/smbserver.py", line 3941, in __init__
    socketserver.TCPServer.__init__(self, server_address, handler_class)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address

**Comment by gwqreqherytr** [comment]
my question

**Comment by gwqreqherytr** [comment]
[*] HTTP server returned status code 200, treating as a successful login
[*] Generating CSR...
[*] CSR generated!
[*] Getting certificate...
[-] Error getting certificate! Make sure you have entered valid certiface template.

**Comment by itayyashar** [comment]
Does anyone know how to solve the following problem with krbrelayx please ?  

Exception occurred during processing of request from ('192.168.80.134', 54298)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()                        
  File "/home/parrot/CRTO/tools/krbrelayx/lib/servers/dnsrelayserver.py", line 54, in handle
    self.do_relay(authdata)
  File "/home/parrot/CRTO/tools/krbrelayx/lib/servers/dnsrelayserver.py", line 65, in do_relay
    if parsed_target.hostname.lower() == host.lower():
AttributeError: 'NoneType' object has no attribute 'lower'
