### ISSUE TITLE
TypeError: initConnection() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by codeitch** [dirkjanm/krbrelayx#27]
I am getting the following error when trying kerberos relaying: 
 
[*] DNS: Client sent authorization
----------------------------------------
Exception happened during processing of request from ('10.191.128.155', 53073)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/ubuntu/krbrelayx/lib/servers/dnsrelayserver.py", line 54, in handle
    self.do_relay(authdata)
  File "/home/ubuntu/krbrelayx/lib/servers/dnsrelayserver.py", line 68, in do_relay
    client.initConnection(authdata, self.server.config.dcip)
TypeError: initConnection() takes 1 positional argument but 3 were given
----------------------------------------`
 
For the sake of completness, I have installed the latest impacket, ldap3, dnspython and pulled the most recent krbrelayx. 
 
I appreciate greatly any hints or tips on this.

**Comment by udp-tunnel** [comment]
I have the same issue

**Comment by udp-tunnel** [comment]
Hi @dirkjanm ,

Can confirm it works. Thanks!!

**Comment by dirkjanm** [comment]
thanks for confirming, will close the issue
