### ISSUE TITLE
ADDSPN error

### ISSUE THREAD

**Issue by igotunj** [dirkjanm/krbrelayx#4]
Hello,
I'm getting the following error when trying to run the addspn.py script on the host with unconstrained delegation

python addspn.py -u <machine account$> -p <NTLM> -s HOST/test.internal.corp -q DC 

[-] Connecting to host...
[-] Binding to host
[+] Bind OK
[+] Found modification target
Traceback (most recent call last):
  File "addspn.py", line 144, in <module>
    main()
  File "addspn.py", line 104, in main
    from impacket.ldap.ldaptypes import SR_SECURITY_DESCRIPTOR
ImportError: No module named ldaptypes

python3 addspn.py -u <machine account$> -p <NTLM> -s HOST/test.internal.corp -q DC 
[-] Connecting to host...
[-] Binding to host
[+] Bind OK
[+] Found modification target
Traceback (most recent call last):
  File "addspn.py", line 144, in <module>
    main()
  File "addspn.py", line 104, in main
    from impacket.ldap.ldaptypes import SR_SECURITY_DESCRIPTOR
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
  File "/usr/local/lib/python3.7/dist-packages/impacket-0.9.19-py3.7.egg/impacket/ldap/ldaptypes.py", line 192
    GENERIC_READ            = 0x80000000L
                                        ^
SyntaxError: invalid syntax

Using impacket version 0.9.19

Tried installing the python dependencies 
apt-get install libsasl2-dev python-dev libldap2-dev libssl-dev

and pip3 install pyldap 

and pip3 install python-ldap

**Comment by dirkjanm** [comment]
Good to hear! Closing this one.
